<?php
/** @var \AHT\Checkout\Block\Template $block */
$order = $block->getOrder();
?>
<div class="admin__page-section order-view-billing-shipping" >
    <div class="admin__page-section-title">
        <span class="title">Delivery Information</span>
        <div class="actions"><?= /* @noEscape */ $block->getDeliveryEditLink($order->getData('order_id')); ?></div>
    </div>
    <div class="admin__page-section-content" style="margin-bottom:30px">
        <p>Date:     <?= substr($order->getData('delivery_date'), 0,10)?></p>
        <p>Comment:  <?= $order->getData('delivery_comment')?></p>
    </div>